---
title: "Table 1: Population Characteristics"
output: html_document
date: "2025-03-21"
author: jaegerl
---

```{r setup, include=FALSE}
# define paths
# for data import
import_path <- "02_data/01_raw_data/"
# for export of inspection objects (spreadsheets)
inspect_path <- "03_spreadsheets/"
# for export of clean data
clean_path <- "02_data/02_clean_data/"
# for tables
table_path <- "04_tables/"
# for figures
figure_path <- "05_figures/"

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(rio)
library(tableone)
library(vcd)

knitr::opts_knit$set(root.dir = normalizePath(".."))
```


## Population Dataset ####

```{r population1}
# patient population and TBI diagnoses
load(paste0(clean_path, "Diagnosis_cleaned.RData"))
setDT(Diagnosis_cleaned)
# demographics, hospital stay, ICU stay
load(paste0(clean_path, "patients_clean.RData"))
# pathophysiology at admission
load(paste0(clean_path, "vitals_clean.RData"))
load(paste0(clean_path, "lab_clean.RData"))
# trauma scores
load(paste0(clean_path, "iss_clean.RData"))
load(paste0(clean_path, "mapping_cleaned.RData"))
# interventions
load(paste0(clean_path, "interventions1_wide.RData"))

# get demographics into the population
diagnoses <- c("bleeding", "fracture", "concussion",
               "brain_edema", "brain_compression",
               "unconsciousness")
Diagnosis_cleaned[, (diagnoses) := lapply(.SD, \(x) as.integer(as.character(x))),
                  .SDcols = diagnoses]
population <- merge(Diagnosis_cleaned[, .(research_case_id,
                                          date,
                                          bleeding,
                                          fracture,
                                          concussion,
                                          brain_edema,
                                          brain_compression,
                                          unconsciousness)],
                    y = patients_clean[, .(research_case_id,
                                           age, elderly, sex,
                                           stay_days, icu, icu_days,
                                           death, death_days)],
                    by = "research_case_id",
                    all.x = TRUE)
# identify those with TBI in a separate dataset with the diagnoses
tbi <- Diagnosis_cleaned[bleeding + fracture + concussion + 
                           brain_edema + brain_compression +
                           unconsciousness > 0]
population[, tbi := as.integer(research_case_id %in% tbi$research_case_id)]
# get vitals of patients
population <- merge(x = population,
                    y = vitals_clean,
                    by = "research_case_id",
                    all.x = TRUE)
# get lab data of patients
population <- merge(x = population,
                    y = lab_clean_wide,
                    by = "research_case_id",
                    all.x = TRUE)
# get ISS of patients
population <- merge(x = population,
                    y = iss_clean,
                    by = "research_case_id",
                    all.x = TRUE)

# calculate region AIS of each patient as maximum AIS value for that region
ais <- mapping_cleaned[, .(ais = max(MAX_AIS_SEVERITY)),
                       by = .(research_case_id,
                              AIS_CHAPTER)]
# define the names of the ais regions
ais_regions <- data.table(
  AIS_CHAPTER = -1:9,
  ais_region = c("No Map", "Other Trauma",
                 "Head", "Face", "Neck",
                 "Thorax", "Abdomen", "Spine",
                 "Upper Extremity", "Lower Extremity", "Unspecified"))
ais <- merge(ais,
             y = ais_regions,
             by = "AIS_CHAPTER",
             all.x = TRUE)
table(ais$ais_region)
# convert to a wide table
ais <- dcast(ais, research_case_id ~ ais_region, value.var = "ais")
ais <- ais[, mget(c("research_case_id", ais_regions$ais_region))]
# merge into population data
population <- merge(population,
                    ais,
                    by = "research_case_id",
                    all.x = TRUE)
# identify those with missing values
population[, `:=`(novital = as.integer(!(research_case_id %in% 
                                           vitals_clean$research_case_id)),
                  nolab = as.integer(!research_case_id %in%
                                       lab_clean_wide$research_case_id),
                  noais = as.integer(!(research_case_id %in%
                                         ais$research_case_id)),
                  noiss = as.integer(is.na(iss)))]

# identify patients with polytrauma as AIS > 0 in at least two body regions
polytrauma <- mapping_cleaned[MAX_AIS_SEVERITY > 0 & AIS_CHAPTER != 1
][, .(n_regions = n_distinct(AIS_CHAPTER)),
  by = .(research_case_id)]
population <- merge(population,
                    y = polytrauma,
                    by = "research_case_id",
                    all.x = TRUE)
population[is.na(n_regions), n_regions := 0]
population[, polytrauma := as.integer(n_regions >= 2)]

# define pathophysiology indicators
population[, `:=`(hypotension = as.integer(bp < 60),
                  tachycardia = as.integer(hr > 100),
                  acidosis = as.integer(lactate > 2),
                  severethoracic = as.integer(Thorax >= 2),
                  majortrauma = as.integer(iss >= 15),
                  anemia = as.integer(hemoglobin < 80),
                  coagulopathy = as.integer(inr >= 1.4),
                  hypothermia = as.integer(temperature < 35))]
# I guess that for all of these indicators, not measured can be regarded as 
# absent...
pph <- c("hypotension", "tachycardia", "anemia",
         "severethoracic", "majortrauma",
         "acidosis", "coagulopathy", 
         "hypothermia")
population[, (pph) := lapply(.SD, \(x) ifelse(is.na(x), 0, x)), .SDcols = pph]

# categorize GCS
population[, gcs_cat := case_when(
  is.na(gcs) ~ "0.unknown",
  gcs >= 13 ~ "1.mild",
  gcs >= 9 ~ "2.moderate",
  gcs <=8 ~ "3.severe")]

# identify presence of invasive intervention
interventions1_wide[, invasive := as.integer(
  rowSums(interventions1_wide[, .SD, .SDcols = !c(1, 2)]) > 0)]
population <- merge(x = population,
                    y = interventions1_wide[, .(research_case_id,
                                                invasive)],
                    by = "research_case_id",
                    all.x = TRUE)
# as discussed with the client, those without a record of interventions simply
# had no intervention
population[is.na(invasive), invasive := 0]

saveRDS(population, 
        file = paste0(clean_path, "population.RDS"))
```

See [here](https://www.aaam.org/wp-content/uploads/2017/06/ICD-ISS-Map_Instructions_May_2017.pdf) for the names of the AIS body regions.


## Table 1: All Cases

Overall characteristics of all patients in the data set.

```{r table1}
table1 <- CreateTableOne(data = population,
                         vars = c("age", "sex", "tbi",
                                  "stay_days", "death",
                                  "iss", "gcs_cat",
                                  pph, "invasive",
                                  "novital", "nolab", "noais", "noiss"),
                         factorVars = c("tbi", "death",
                                        pph, "invasive",
                                        "novital", "nolab", "noais", "noiss")) |> 
  print(nonnormal = c("age", "stay_days", "iss"),
        printToggle = FALSE,
        noSpaces = TRUE) |> 
  data.frame() |> 
  rownames_to_column(var = "Characteristic")
table1
```


Also make a table stratified by TBI and non-TBI patients

```{r table1_stratified}
table1tbi <- CreateTableOne(data = population,
                            strata = "tbi",
                            vars = c("age", "sex",
                                     "stay_days", "death",
                                     "Head", "iss", "gcs_cat",
                                     pph, "invasive",
                                     "novital", "nolab", "noais", "noiss"),
                            factorVars = c("death", "Head",
                                           pph, "invasive",
                                           "novital", "nolab", "noais", "noiss")) |> 
  print(nonnormal = c("age", "stay_days", "iss"),
        printToggle = FALSE,
        noSpaces = TRUE, test = FALSE) |> 
  data.frame() |> 
  rownames_to_column(var = "Characteristic")
colnames(table1tbi)[2:3] <- c("No TBI", "TBI")
table1tbi
```


## Table 1: Polytrauma Cases Only

```{r table1_polytrauma}
table1_polytrauma <- CreateTableOne(data = population[polytrauma == 1],
                                    includeNA = TRUE,
                                    vars = c("age", "sex", "tbi",
                                             "stay_days", "death",
                                             "iss", "gcs_cat",
                                             pph, "invasive",
                                             "novital", "nolab", "noais", "noiss"),
                                    factorVars = c("tbi", "death",
                                                   pph, "invasive",
                                                   "novital", "nolab", "noais", "noiss")) |> 
  print(nonnormal = c("age", "stay_days", "iss"),
        printToggle = FALSE,
        noSpaces = TRUE) |> 
  data.frame() |> 
  rownames_to_column(var = "Characteristic")
table1_polytrauma
```
```{r table1_polytrauma_stratified}
table1tbi_polytrauma <- CreateTableOne(data = population[polytrauma == 1],
                                       strata = "tbi",
                                       vars = c("age", "sex",
                                                "stay_days", "death",
                                                "Head", "iss",
                                                pph, "gcs_cat",
                                                "invasive",
                                                "novital", "nolab"),
                                       factorVars = c("death", "Head",
                                                      pph, "invasive",
                                                      "novital", "nolab"),
                                       
                                       includeNA = TRUE) |> 
  print(nonnormal = c("age", "stay_days", "iss"),
        printToggle = FALSE,
        noSpaces = TRUE, test = FALSE) |> 
  data.frame() |> 
  rownames_to_column(var = "Characteristic")
colnames(table1tbi_polytrauma)[2:3] <- c("No TBI", "TBI")
table1tbi_polytrauma
```